image: ilaborie/hugonode

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - hugo version
  - echo node `node --version`
  - echo yarn `yarn --version`
  - pushd themes/devfest-theme-hugo
  - yarn
  - popd

prod:
  variables:
    HUGO_ENV: production
  script:
    - hugo --baseURL https://devfest.gdgvl.ru/
    - node themes/devfest-theme-hugo/minify.js
    - firebase deploy --token "$FIREBASE_PROD_TOKEN"
  artifacts:
    paths:
      - public
  only:
    - master
