baseURL = "https://sandbox-devfesttoulouse.firebaseapp.com/"
languageCode = "fr-FR"
title = "Devfest Toulouse 2019"

# Theme
theme = "devfest-theme-hugo"

# Params

enableEmoji = true
enableRobotsTXT = true

log = true
verbose = true

googleAnalytics = "UA-37717223-7"

[params]
    favicon = "/images/favicon.ico"
    themeColor = "#673ab7"
    title = "DevFest Toulouse 2019"
    date = "2019-10-03"
    description = "Le DevFest, ou 'Developers Festival', est une conférence technique destinée aux développeurs. Elle s'adresse aussi bien aux étudiants, aux professionnels ou tout simplement aux curieux technophiles."
    images = ["/images/logo.svg", "/images/logo-monochrome.svg"]
    email = "contact@devfesttoulouse.fr"
    keywords = "event, gdg, gde, devfest, google, programming, android, chrome, developers, web, cloud, androiddev"

[params.logos]
    header = "/images/logo.svg"
    footer = "/images/logo-monochrome.svg"


[[params.menus]]
    name = "Accueil"
    url = "/"

[[params.menus]]
    name = "Partners"
    url = "/partners"

[[params.menus]]
    name = "Sessions"
    url = "/talks/"

[[params.menus]]
    name = "Speakers"
    url = "/speakers/"

[[params.menus]]
    name = "Équipe"
    url = "/team/"

[[params.menus]]
    name = "Blog"
    url = "/blog/"

[[params.menus]]
    name = "FAQ"
    url = "/faq/"

[[params.menus]]
    name = "Jobs"
    url = "https://jobs.devfesttoulouse.fr/"


[taxonomies]
  tag = "tags"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = true
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = true
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false
