baseURL = "https://sandbox-devfesttoulouse.firebaseapp.com/"
languageCode = "fr-FR"
title = "Devfest Toulouse 2019"

# Theme
theme = "devfest-theme-hugo"

# Params

enableEmoji = true
enableRobotsTXT = true

log = true
verbose = true

googleAnalytics = "UA-37717223-7"

[params]
    favicon = "/images/favicon.ico"
    themeColor = "#673ab7"
    title = "DevFest Toulouse 2019"
    date = "2019-10-03"
    description = "Le DevFest, ou 'Developers Festival', est une conférence technique destinée aux développeurs. Elle s'adresse aussi bien aux étudiants, aux professionnels ou tout simplement aux curieux technophiles."
    images = ["/images/logo.svg", "/images/logo-monochrome.svg"]
    email = "contact@devfesttoulouse.fr"
    keywords = "event, gdg, gde, devfest, google, programming, android, chrome, developers, web, cloud, androiddev"

[params.logos]
    header = "/images/logo.svg"
    footer = "/images/logo-monochrome.svg"

[params.location]
  name = "Centre de Congrès Pierre Baudis"
  description = "Le Centre de Congrès Pierre Baudis est un lieu d'échanges moderne, situé sur un emplacement privilégié, à proximité immédiate du centre de Toulouse et dans un environnement verdoyant."
  address = "11 Espl. Compans Caffarelli, 31000 Toulouse"
[params.location.pointer ]
  latitude = 43.6110956
  longitude = 1.4332799

[params.map]
    googleMapsAPIKey = "AIzaSyAsYarycfx4sV9QhauT5li-63snSTqoJ3g"
    latitude = 48
    longitude = 8
    zoom = 5
    options = '''{
  "disableDefaultUI": true,
  "disableDoubleClickZoom": true,
  "scrollwheel": false,
  "draggable": false,
  "styles": [{
    "stylers": [{
        "lightness": 40
      },
      {
        "visibility": "on"
      },
      {
        "gamma": 0.9
      },
      {
        "weight": 0.4
      }
    ]
  }, {
    "elementType": "labels",
    "stylers": [{
      "visibility": "on"
    }]
  }, {
    "featureType": "water",
    "stylers": [{
      "color": "#5dc7ff"
    }]
  }, {
    "featureType": "road",
    "stylers": [{
      "visibility": "off"
    }]
  }]
}'''

[taxonomies]
  tag = "tags"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = true
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = true
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false
