baseURL = "http://example.org/"
languageCode = "fr-FR"
title = "Devfest Toulouse 2019"

# Theme
#theme = "test-theme-hugo"
theme = "ga-hugo-theme"

# Params

enableEmoji = true
enableRobotsTXT = true

log = true
verbose = true



# Privacy
[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false
